### ISSUE TITLE
BelongsToThrough with custom ForeignKey

### ISSUE THREAD

**Issue by hiddenrebel** [znck/belongs-to-through#23]
I have structure table with custom foreignKey name `owner_id`

``` yaml
users:
  id: unsigned int, primary

properties:
  id : unsigned int, primary
  name: string
  owner_id: unsigned int, foreign(users)

periods:
  id: unsigned int, primary
  property_id : unsigned int, foreign(properties)
  date: date

activities:
  id : unsigned int, primary
  name : string
  period_id : unsigned int, foreign(periods)
```
but when i'm using BelongsToThrough relation:

``` php
class Activity {
    public function owner()
    {
        return $this->belongsToThrough('App\User',['App\Property','App\Period']);
    }
}
```
there's error because query search for `user_id` in table `Property` not `owner_id`.

is there any option that i could set custom foreignKey?
